// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ljcowwownsjepogxpick.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxqY293d293bnNqZXBvZ3hwaWNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MDI0MjMsImV4cCI6MjA2NzQ3ODQyM30.TTSqCvMjpvFG7IS0tFmAEo75k3q_d3URoqfYInD-Nq8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});